### PR TITLE
add fallback handling for invalid iDisplayLength and iDisplayStart

### PR DESCRIPTION
**Pull request by xflr6**
- fix ValueError: invalid literal for int() with base 10: 'NaN'

### CODE REVIEW

**Comment by xflr6** [comment]
Yep (see the `glottolog3` Exception `2018-01-15 01:31:58,155`, might have been hand-crafted though).

**Comment by xrotwang** [comment]
An explicit test may have been nice :)

**Comment by xrotwang** [comment]
I like test-driven for bug-fixes

**Comment by xflr6** [comment]
Sure, will do (that's what the review is for :)

**Comment by xflr6** [comment]
Here you go: https://github.com/clld/clld/commit/ceedfac33a473607a803c060b99dce17f512f82d

**Pull request merged**
